[package]
name = "heart7"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "heart7d"
path = "src/bin/server.rs"

[[bin]]
name = "heart7"
path = "src/bin/client.rs"

[dependencies]
tonic = "0.9"
prost = "0.11"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tonic-build = "0.9"
