[package]
name = "heart7_rule"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
thiserror = "1"
tonic = "0.12.3"
prost = "0.13.4"

[build-dependencies]
tonic-build = { version = "0.12", features = ["prost"]}
